# Generated by Django 2.2.3 on 2019-07-21 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_sum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sum',
            new_name='summary',
        ),
    ]
